In [1]:
# Exp No:2

In [2]:
# Aim:To perfrom simple linear regression and find out the coefficients of it.

In [3]:
# Name:Sujal Ramesh Lothe
# Roll No:39
# subject:Data Science and Statistics
# Class:B 

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [5]:
import os 

In [6]:
os.getcwd()

'C:\\Users\\bhush'

In [7]:
os.chdir("C:\\Users\\bhush\\OneDrive\\Desktop")

In [8]:
df=pd.read_csv("C:\\Users\\bhush\\OneDrive\\Desktop\\Salary_Data.csv.xls")

In [9]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [10]:
df.tail()

YearsExperience  Salary
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [11]:
df.head(30)

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [12]:
df[5:10]

YearsExperience  Salary
5              2.9   56642
6              3.0   60150
7              3.2   54445
8              3.2   64445
9              3.7   57189

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes


In [14]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [15]:
df.shape

(30, 2)

In [16]:
df.size

60

In [17]:
df.ndim

2

In [18]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [19]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [20]:
# Assiging values in X & Y
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


#x=df['year of experience']
#y=df['salary']

In [21]:
print(x)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [22]:
print(y)

[ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]


In [23]:
# Splitting testdata into x_train,x_test,y_train,y_test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.3,random_state=42)

In [24]:
print(x_train)

[[ 1.1]
 [ 2.2]
 [ 5.1]
 [ 2.9]
 [ 4.1]
 [ 4. ]
 [ 7.9]
 [ 1.3]
 [ 1.5]
 [ 9. ]
 [ 2. ]
 [ 7.1]
 [ 9.5]
 [ 5.9]
 [10.5]
 [ 6.8]
 [ 3.2]
 [ 3.9]
 [ 4.5]
 [ 6. ]
 [ 3. ]]


In [25]:
print(x_test)

[[ 9.6]
 [ 4.9]
 [ 8.2]
 [ 5.3]
 [ 3.2]
 [ 3.7]
 [10.3]
 [ 8.7]
 [ 4. ]]


In [26]:
print(y_train)

[ 39343  39891  66029  56642  57081  55794 101302  46205  37731 105582
  43525  98273 116969  81363 121872  91738  54445  63218  61111  93940
  60150]


In [27]:
print(y_test)

[112635  67938 113812  83088  64445  57189 122391 109431  56957]


In [28]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [29]:
#Assigning Coefficient (slope) to m
m = lr.coef_

In [30]:
print("Coefficient  :" , m)

Coefficient  : [9339.08172382]


In [31]:
#Assigning Y-intercept to a
c = lr.intercept_

In [32]:
print("Intercept : ", c)

Intercept :  25918.438334893202


In [33]:
lr.score(x_test,y_test) * 100

94.14466227178214

In [34]:
df.isnull().any()

YearsExperience    False
Salary             False
dtype: bool